# Generated by Django 4.1.7 on 2023-03-31 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('upfront_commission', models.DecimalField(decimal_places=4, max_digits=7)),
                ('high_trail_commission', models.DecimalField(decimal_places=4, max_digits=7)),
                ('low_trail_commission', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('balance_multiplier', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
            ],
        ),
    ]
